# Generated by Django 5.0.3 on 2024-03-24 12:10

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                (
                    "stakeholderID",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("password", models.CharField(default="", max_length=400)),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Mobile Number"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=150, verbose_name="last name"
                    ),
                ),
                ("address", models.TextField(default="", verbose_name="Address")),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                ("token", models.CharField(default="", max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("warden", "Warden"),
                            ("hall_clerk", "Hall Clerk"),
                            ("hmc_chairman", "HMC Chairman"),
                            ("mess_manager", "Mess Manager"),
                            ("admin", "Administrator"),
                            ("admission", "Admission Unit"),
                            ("hall_employee", "Hall Employee"),
                        ],
                        default="student",
                        max_length=40,
                        verbose_name="Role",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Name"),
                ),
                (
                    "max_occupancy",
                    models.IntegerField(default=0, verbose_name="max_occupancy"),
                ),
                (
                    "current_occupancy",
                    models.IntegerField(default=0, verbose_name="current_occupancy"),
                ),
                (
                    "no_of_rooms",
                    models.IntegerField(default=0, verbose_name="no_of_rooms"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_hall",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallPassbook",
            fields=[
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000000,
                        max_digits=10,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "hall",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hall_passbook",
                        serialize=False,
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessPassbook",
            fields=[
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=500000,
                        max_digits=8,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "hall",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mess_passbook",
                        serialize=False,
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WardenPassbook",
            fields=[
                (
                    "hall",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="warden_passbook",
                        serialize=False,
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Amenity_Name"
                    ),
                ),
                ("established_date", models.DateField(default=datetime.datetime.now)),
                (
                    "total_price",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="amenity_price"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_amenity",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("jan", "January"),
                            ("feb", "February"),
                            ("mar", "March"),
                            ("apr", "April"),
                            ("may", "May"),
                            ("jun", "June"),
                            ("jul", "July"),
                            ("aug", "August"),
                            ("sep", "September"),
                            ("oct", "October"),
                            ("nov", "November"),
                            ("dec", "December"),
                        ],
                        max_length=20,
                        verbose_name="Month",
                    ),
                ),
                (
                    "monday_breakfast",
                    models.CharField(
                        default="A", max_length=50, verbose_name="Monday Breakfast"
                    ),
                ),
                (
                    "monday_lunch",
                    models.CharField(
                        default="B", max_length=50, verbose_name="Monday Lunch"
                    ),
                ),
                (
                    "monday_snacks",
                    models.CharField(
                        default="C", max_length=50, verbose_name="Monday Snacks"
                    ),
                ),
                (
                    "monday_dinner",
                    models.CharField(
                        default="D", max_length=50, verbose_name="Monday Dinner"
                    ),
                ),
                (
                    "tuesday_breakfast",
                    models.CharField(
                        default="E", max_length=50, verbose_name="Tuesday Breakfast"
                    ),
                ),
                (
                    "tuesday_lunch",
                    models.CharField(
                        default="A1", max_length=50, verbose_name="Tuesday Lunch"
                    ),
                ),
                (
                    "tuesday_snacks",
                    models.CharField(
                        default="F", max_length=50, verbose_name="Tuesday Snacks"
                    ),
                ),
                (
                    "tuesday_dinner",
                    models.CharField(
                        default="G", max_length=50, verbose_name="Tuesday Dinner"
                    ),
                ),
                (
                    "wednesday_breakfast",
                    models.CharField(
                        default="H", max_length=50, verbose_name="Wednesday Breakfast"
                    ),
                ),
                (
                    "wednesday_lunch",
                    models.CharField(
                        default="I", max_length=50, verbose_name="Wednesday Lunch"
                    ),
                ),
                (
                    "wednesday_snacks",
                    models.CharField(
                        default="J", max_length=50, verbose_name="Wednesday Snacks"
                    ),
                ),
                (
                    "wednesday_dinner",
                    models.CharField(
                        default="K", max_length=50, verbose_name="Wednesday Dinner"
                    ),
                ),
                (
                    "thursday_breakfast",
                    models.CharField(
                        default="J1", max_length=50, verbose_name="Thursday Breakfast"
                    ),
                ),
                (
                    "thursday_lunch",
                    models.CharField(
                        default="L", max_length=50, verbose_name="Thursday Lunch"
                    ),
                ),
                (
                    "thursday_snacks",
                    models.CharField(
                        default="M", max_length=50, verbose_name="Thursday Snacks"
                    ),
                ),
                (
                    "thursday_dinner",
                    models.CharField(
                        default="N", max_length=50, verbose_name="Thursday Dinner"
                    ),
                ),
                (
                    "friday_breakfast",
                    models.CharField(
                        default="O", max_length=50, verbose_name="Friday Breakfast"
                    ),
                ),
                (
                    "friday_lunch",
                    models.CharField(
                        default="P", max_length=50, verbose_name="Friday Lunch"
                    ),
                ),
                (
                    "friday_snacks",
                    models.CharField(
                        default="Q", max_length=50, verbose_name="Friday Snacks"
                    ),
                ),
                (
                    "friday_dinner",
                    models.CharField(
                        default="R", max_length=50, verbose_name="Friday Dinner"
                    ),
                ),
                (
                    "saturday_breakfast",
                    models.CharField(
                        default="S", max_length=50, verbose_name="Saturday Breakfast"
                    ),
                ),
                (
                    "saturday_lunch",
                    models.CharField(
                        default="T", max_length=50, verbose_name="Saturday Lunch"
                    ),
                ),
                (
                    "saturday_snacks",
                    models.CharField(
                        default="U", max_length=50, verbose_name="Saturday Snacks"
                    ),
                ),
                (
                    "saturday_dinner",
                    models.CharField(
                        default="V", max_length=50, verbose_name="Saturday Dinner"
                    ),
                ),
                (
                    "sunday_breakfast",
                    models.CharField(
                        default="W", max_length=50, verbose_name="Sunday Breakfast"
                    ),
                ),
                (
                    "sunday_lunch",
                    models.CharField(
                        default="X", max_length=50, verbose_name="Sunday Lunch"
                    ),
                ),
                (
                    "sunday_snacks",
                    models.CharField(
                        default="Y", max_length=50, verbose_name="Sunday Snacks"
                    ),
                ),
                (
                    "sunday_dinner",
                    models.CharField(
                        default="Z", max_length=50, verbose_name="Sunday Dinner"
                    ),
                ),
                (
                    "hall",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_menu",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("content", models.TextField(default="")),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
                ("image", models.ImageField(default="default.jpg", upload_to="")),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_notices",
                        to="main.hall",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notices",
            },
        ),
        migrations.CreateModel(
            name="Ration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item1",
                    models.CharField(blank=True, max_length=20, verbose_name="Item 1"),
                ),
                ("qt1", models.IntegerField(blank=True, verbose_name="qt1")),
                ("rate1", models.IntegerField(blank=True, verbose_name="qt1")),
                (
                    "item2",
                    models.CharField(blank=True, max_length=20, verbose_name="Item "),
                ),
                ("qt2", models.IntegerField(blank=True, verbose_name="qt2")),
                ("rate2", models.IntegerField(blank=True, verbose_name="rt2")),
                (
                    "item3",
                    models.CharField(blank=True, max_length=20, verbose_name="Item 3"),
                ),
                ("qt3", models.IntegerField(blank=True, verbose_name="qt3")),
                ("rate3", models.IntegerField(blank=True, verbose_name="rt3")),
                (
                    "item4",
                    models.CharField(blank=True, max_length=20, verbose_name="Item 4"),
                ),
                ("qt4", models.IntegerField(blank=True, verbose_name="qt4")),
                ("rate4", models.IntegerField(blank=True, verbose_name="rt4")),
                (
                    "item5",
                    models.CharField(blank=True, max_length=20, verbose_name="Item 5"),
                ),
                ("qt5", models.IntegerField(blank=True, verbose_name="qt5")),
                ("rate5", models.IntegerField(blank=True, verbose_name="rt5")),
                ("total", models.IntegerField(blank=True, verbose_name="total")),
                (
                    "hall",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_ration",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_room",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallEmployee",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hall_employee",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("gardener", "Garderner"),
                            ("plumber", "Plumber"),
                            ("electrician", "Electrician"),
                            ("hall_canteen", "Hall Canteen"),
                            ("sweeper", "Sweeper"),
                            ("mess worker", "Mess Worker"),
                            ("security", "Security"),
                            ("cook", "Cook"),
                        ],
                        default="Mess Worker",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(
                        choices=[
                            (1000, "1000"),
                            (2000, "2000"),
                            (5000, "5000"),
                            (10000, "10000"),
                            (15000, "15000"),
                            (20000, "20000"),
                        ],
                        default=2000,
                        verbose_name="Salary",
                    ),
                ),
                (
                    "monthly_leaves",
                    models.IntegerField(default=0, verbose_name="monthly leaves taken"),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_hall",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallManager",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hall_manager",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_hall",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessManager",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mess_manager",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_hall",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPassbook",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_passbook",
                        serialize=False,
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(default="")),
                ("date_created", models.DateField(default=datetime.datetime.now)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="uploads/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("mess", "Mess"),
                            ("room condition", "Room Condition"),
                            ("plumbing", "plumbing"),
                            ("health", "Health"),
                        ],
                        default="maintenance",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_complaints",
                        to="main.hall",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_complaints",
                        to="main.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Complaint",
            },
        ),
        migrations.CreateModel(
            name="Warden",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="warden",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        default="", max_length=50, verbose_name="Department"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        default="", max_length=200, verbose_name="Designation"
                    ),
                ),
                (
                    "posts_held",
                    models.CharField(
                        default="", max_length=500, verbose_name="Posts Held"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warden",
                        to="main.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ATR",
            fields=[
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="complaint",
                        serialize=False,
                        to="main.complaint",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("report", models.TextField(default="No Action Taken")),
                (
                    "employee",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_employee",
                        to="main.hallemployee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "expenditure",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Hall Expenditure",
                    ),
                ),
                (
                    "hall_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_expenditure",
                        to="main.hallpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "expenditure",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Mess Expenditure",
                    ),
                ),
                (
                    "mess_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_expenditure",
                        to="main.messpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "fulfilled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Fulfilled",
                    ),
                ),
                (
                    "student_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payment",
                        to="main.studentpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Due",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "demand",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Demand"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mess", "Mess Dues"),
                            ("hostel", "Hostel Dues"),
                            ("amenity", "Amenity Dues"),
                        ],
                        default="mess",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "student_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues",
                        to="main.studentpassbook",
                    ),
                ),
            ],
        ),
    ]
