# Generated by Django 5.0.3 on 2024-03-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=400),
        ),
    ]
