# Generated by Django 5.0.3 on 2024-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardenpassbook",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, default=2000000, max_digits=10, verbose_name="Budget"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("warden", "Warden"),
                    ("hall_manager", "Hall Manager"),
                    ("hmc_chairman", "HMC Chairman"),
                    ("mess_manager", "Mess Manager"),
                    ("admin", "Administrator"),
                    ("admission", "Admission Unit"),
                    ("hall_employee", "Hall Employee"),
                ],
                default="student",
                max_length=40,
                verbose_name="Role",
            ),
        ),
    ]
