# Generated by Django 5.0.3 on 2024-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_hallmanager_options_alter_hmc_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallmanager',
            options={'permissions': [('is_hall_manager', 'is_hall_manager'), ('is_hall', 'is_hall')]},
        ),
        migrations.AlterModelOptions(
            name='warden',
            options={'permissions': [('is_warden', 'is_warden'), ('is_hall', 'is_hall')]},
        ),
    ]
