# Generated by Django 5.0.3 on 2024-03-25 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_wardenpassbook_budget_alter_client_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WardenPassbook",
        ),
    ]
