# Generated by Django 5.0.3 on 2024-03-25 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_menu_id_remove_ration_id_messexpenditure_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hallemployee",
            name="hall",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_hall",
                to="main.hall",
            ),
        ),
        migrations.AlterField(
            model_name="hallemployee",
            name="role",
            field=models.CharField(
                choices=[
                    ("gardener", "Garderner"),
                    ("plumber", "Plumber"),
                    ("electrician", "Electrician"),
                    ("hall_canteen", "Hall Canteen"),
                    ("sweeper", "Sweeper"),
                    ("security", "Security"),
                ],
                default="Mess Worker",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="MessEmployee",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mess_employee",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("utensils", "Wash Utensils"),
                            ("cook", "Cook"),
                            ("sweeper", "Sweeper"),
                        ],
                        default="Mess Worker",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(
                        choices=[
                            (1000, "1000"),
                            (2000, "2000"),
                            (5000, "5000"),
                            (10000, "10000"),
                            (15000, "15000"),
                            (20000, "20000"),
                        ],
                        default=2000,
                        verbose_name="Salary",
                    ),
                ),
                (
                    "monthly_leaves",
                    models.IntegerField(default=0, verbose_name="monthly leaves taken"),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_employee_hall",
                        to="main.hall",
                    ),
                ),
            ],
        ),
    ]
