# Generated by Django 5.0.3 on 2024-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hallmanager_options_alter_warden_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messmanager',
            options={'permissions': [('is_mess_manager', 'is_mess_manager'), ('is_mess', 'is_mess')]},
        ),
        migrations.AlterModelOptions(
            name='warden',
            options={'permissions': [('is_warden', 'is_warden')]},
        ),
    ]
