# Generated by Django 5.0.3 on 2024-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_dues_hall_client_token_alter_client_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="role",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("mess", "Mess"),
                    ("room condition", "Room Condition"),
                    ("plumbing", "plumbing"),
                    ("health", "Health"),
                ],
                default="maintenance",
                max_length=40,
                verbose_name="Role",
            ),
        ),
    ]
