# Generated by Django 5.0.3 on 2024-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hallemployee_hall_alter_hallemployee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallexpenditure',
            name='type',
            field=models.CharField(choices=[('salaries', 'Salaries'), ('amenities', 'Amenities')], default='salaries', max_length=100, verbose_name='Type'),
        ),
    ]
