# Generated by Django 5.0.3 on 2024-03-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_delete_wardenpassbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardenPassbook",
            fields=[
                (
                    "hall",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="warden_passbook",
                        serialize=False,
                        to="main.hall",
                    ),
                ),
                (
                    "original_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=20000000,
                        max_digits=10,
                        verbose_name="original_budget",
                    ),
                ),
                (
                    "current_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=20000000,
                        max_digits=10,
                        verbose_name="current_budget",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="messexpenditure",
            name="mess_passbook",
        ),
        migrations.RemoveField(
            model_name="hallpassbook",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="messpassbook",
            name="budget",
        ),
        migrations.CreateModel(
            name="HallTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("salaries", "Salaries"),
                            ("amenities", "Amenities"),
                            ("allotment", "Allotment"),
                        ],
                        default="salaries",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Amount"
                    ),
                ),
                (
                    "hall_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_transaction",
                        to="main.hallpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("salaries", "Salaries"),
                            ("rations", "Rations"),
                            ("allotment", "Allotment"),
                        ],
                        default="salaries",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Amount"
                    ),
                ),
                (
                    "mess_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_transaction",
                        to="main.messpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WardenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hall_allotment", "Hall Allotment"),
                            ("mess_allotment", "Mess Allotment"),
                            ("grant", "Grant"),
                        ],
                        default="salaries",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Amount"
                    ),
                ),
                (
                    "warden_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warden_transaction",
                        to="main.wardenpassbook",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HallExpenditure",
        ),
        migrations.DeleteModel(
            name="MessExpenditure",
        ),
    ]
