# Generated by Django 5.0.3 on 2024-04-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_messmanager_options_alter_warden_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messmanager',
            options={'permissions': [('is_mess_manager', 'is_mess_manager'), ('is_mess', 'is_mess'), ('is_menu', 'is_menu')]},
        ),
    ]
