# Generated by Django 5.0.3 on 2024-03-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_complaint_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.student"
            ),
        ),
    ]
