# Generated by Django 5.0.3 on 2024-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wardenpassbook_remove_messexpenditure_mess_passbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardenpassbook',
            name='current_budget',
        ),
        migrations.RemoveField(
            model_name='wardenpassbook',
            name='original_budget',
        ),
        migrations.AlterField(
            model_name='messtransaction',
            name='type',
            field=models.CharField(choices=[('rations', 'Rations'), ('allotment', 'Allotment')], default='salaries', max_length=100, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='MessEmployee',
        ),
    ]
