# Generated by Django 5.0.3 on 2024-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_messmanager_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="due",
            name="type",
            field=models.CharField(
                choices=[("Mess Dues", "Mess Dues"), ("Hall Dues", "Hall Dues")],
                default="Mess Dues",
                max_length=100,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="hallemployee",
            name="role",
            field=models.CharField(
                choices=[
                    ("gardener", "Garderner"),
                    ("plumber", "Plumber"),
                    ("electrician", "Electrician"),
                    ("hall_canteen", "Hall Canteen"),
                    ("sweeper", "Sweeper"),
                    ("cook", "Cook"),
                    ("security", "Security"),
                    ("mess_worker", "Mess Worker"),
                ],
                default="mess_worker",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
