# Generated by Django 5.0.3 on 2024-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_wardenpassbook_current_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallemployee',
            name='role',
            field=models.CharField(choices=[('gardener', 'Garderner'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('hall_canteen', 'Hall Canteen'), ('sweeper', 'Sweeper'), ('cook', 'Cook'), ('security', 'Security'), ('mess_worker', 'Mess Worker')], default='Mess Worker', max_length=20, verbose_name='Role'),
        ),
    ]
