# Generated by Django 5.0.3 on 2024-03-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_complaint_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hall",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_hall",
                to="main.hall",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_complaints",
                to="main.student",
            ),
        ),
    ]
