# Generated by Django 5.0.3 on 2024-03-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_hallemployee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMC',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hmc', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('budget', models.DecimalField(decimal_places=2, default=2000000, max_digits=10, verbose_name='Budget')),
            ],
        ),
    ]
