# Generated by Django 5.0.3 on 2024-03-22 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_student_hall_alter_complaint_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallManager",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hall_manager",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="client",
            old_name="username",
            new_name="stakeholderID",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_number",
        ),
        migrations.AlterField(
            model_name="notice",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.DeleteModel(
            name="HallClerk",
        ),
    ]
