# Generated by Django 5.0.3 on 2024-04-08 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_due_type_alter_hallemployee_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hmc",
            options={"permissions": [("is_HMC", "is_HMC")]},
        ),
    ]
