# Generated by Django 5.0.3 on 2024-03-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmc',
            name='budget',
        ),
    ]
