# Generated by Django 5.0.3 on 2024-03-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_hallmanager_rename_username_client_stakeholderid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallPassbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPassbook",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_passbook",
                        serialize=False,
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Due",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "demand",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Demand"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mess", "Mess Dues"),
                            ("hostel", "Hostel Dues"),
                            ("amenity", "Amenity Dues"),
                        ],
                        default="mess",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
                (
                    "student_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues",
                        to="main.studentpassbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "fulfilled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Fulfilled",
                    ),
                ),
                (
                    "student_passbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payment",
                        to="main.studentpassbook",
                    ),
                ),
            ],
        ),
    ]
