# Generated by Django 5.0.3 on 2024-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hallpassbook_studentpassbook_payments_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='role',
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('mess', 'Mess'), ('room condition', 'Room Condition'), ('plumbing', 'plumbing'), ('health', 'Health')], default='maintenance', max_length=40, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
