# Generated by Django 5.0.3 on 2024-03-23 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_complaint_role_complaint_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallEmployee',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hall_employee', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('warden', 'Warden'), ('hall_clerk', 'Hall Clerk'), ('hmc_chairman', 'HMC Chairman'), ('mess_manager', 'Mess Manager'), ('admin', 'Administrator'), ('admission', 'Admission Unit'), ('hall_employee', 'Hall Employee')], default='student', max_length=40, verbose_name='Role'),
        ),
    ]
