# Generated by Django 5.0.3 on 2024-03-23 14:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_hallemployee_alter_client_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Amenity_Name')),
                ('established_date', models.DateField(default=datetime.datetime.now)),
                ('total_price', models.IntegerField(blank=True, default=0, verbose_name='amenity_price')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_amenity', to='main.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ATR',
            fields=[
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='complaint', serialize=False, to='main.complaint')),
                ('status', models.BooleanField(default=False)),
                ('report', models.TextField(default='No Action Taken')),
            ],
        ),
        migrations.DeleteModel(
            name='Dues',
        ),
        migrations.AddField(
            model_name='hallemployee',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employer_hall', to='main.hall'),
        ),
        migrations.AddField(
            model_name='hallemployee',
            name='monthly_leaves',
            field=models.IntegerField(default=0, verbose_name='monthly leaves taken'),
        ),
        migrations.AddField(
            model_name='hallemployee',
            name='role',
            field=models.CharField(choices=[('gardener', 'Garderner'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('hall_canteen', 'Hall Canteen'), ('sweeper', 'Sweeper'), ('mess worker', 'Mess Worker'), ('security', 'Security'), ('cook', 'Cook')], default='Mess Worker', max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='hallemployee',
            name='salary',
            field=models.IntegerField(choices=[(1000, '1000'), (2000, '2000'), (5000, '5000'), (10000, '10000'), (15000, '15000'), (20000, '20000')], default=2000, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='hallmanager',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='managee_hall', to='main.hall'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hall_complaints', to='main.hall'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_complaints', to='main.student'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hall_notices', to='main.hall'),
        ),
        migrations.AddField(
            model_name='atr',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='main.hallemployee'),
        ),
    ]
