# Generated by Django 5.0.3 on 2024-03-16 18:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(default="", max_length=50, unique=True)),
                ("password", models.CharField(default="", max_length=50, unique=True)),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Mobile Number"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=150, verbose_name="last name"
                    ),
                ),
                ("address", models.TextField(default="", verbose_name="Address")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("warden", "Warden"),
                            ("hall_clerk", "Hall Clerk"),
                            ("hmc_chairman", "HMC Chairman"),
                            ("mess_manager", "Mess Manager"),
                            ("admin", "Administrator"),
                            ("admission", "Admission Unit"),
                        ],
                        default="student",
                        max_length=40,
                        verbose_name="Role",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "AppUser",
                "verbose_name_plural": "AppUsers",
            },
        ),
        migrations.CreateModel(
            name="HallClerk",
            fields=[
                (
                    "appuser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hall_clerk",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "appuser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollNumber",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Roll Number"
                    ),
                ),
            ],
        ),
    ]
