# Generated by Django 5.0.3 on 2024-03-17 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_appuser_is_staff_alter_appuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="date_joined",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
