# Generated by Django 5.0.3 on 2024-03-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_appuser_date_joined_appuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="password",
            field=models.CharField(default="", max_length=400, unique=True),
        ),
    ]
