# Generated by Django 5.0.3 on 2024-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=8)),
                ("room", models.IntegerField(default=999)),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
