# Generated by Django 5.0 on 2024-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
        migrations.AddField(
            model_name='user',
            name='alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=666),
        ),
    ]
