# Generated by Django 5.0 on 2024-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
