# Generated by Django 5.0 on 2024-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='', max_length=8, unique=True)),
                ('name', models.CharField(default='', max_length=8, unique=True)),
                ('nonveg', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
